<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <Version>0.1.0</Version>
    <Authors>d-kja</Authors>
    <Description>Simple cursor offset filter for OpenTabletDriver. Shifts cursor position by configurable X and Y values.</Description>
    <RepositoryUrl>https://github.com/d-kja/otd-cursor-shift</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTabletDriver.Plugin" Version="0.6.6.0" />
  </ItemGroup>

</Project>
